load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "leetcode",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
)
