# load("@io_bazel_rules_go//go:def.bzl", "go_library")
#
# package(
#     default_visibility = ["//:__subpackages__"],
# )
#
# go_library(
#     name = "leetcode",
#     srcs = glob(["*.go"]),
#     importpath = "github.com/fborowiec/leetcode/go/leetcode",
# )
